# <런 검정>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib
import os
import warnings

warnings.filterwarnings("ignore")

In [2]:
print("""
한개의 샘플이 무작위로 추출되었는지 여부를 검정한다.
런(Run)이란 동일한 관측값이 연속적으로 이어진 것을 말한다. 
즉, 한 종류의 부호 혹은 한 집단이 시작하여 끝날 때까지의 한 덩어리를 의미한다.

범주형 데이터의 경우 각 범주의 개수와 run의 개수를 사용하여 검정을 진행한다.
수치형 데이터의 경우 중앙값을 기준으로 데이터를 이진화 한 후 검정을 진행한다.
""")

한개의 샘플이 무작위로 추출되었는지 여부를 검정한다.
런(Run)이란 동일한 관측값이 연속적으로 이어진 것을 말한다.
즉, 한 종류의 부호 혹은 한 집단이 시작하여 끝날 때까지의 한 덩어리를 의미한다.

범주형 데이터의 경우 각 범주의 개수와 run의 개수를 사용하여 검정을 진행한다.
수치형 데이터의 경우 중앙값을 기준으로 데이터를 이진화 한 후 검정을 진행한다.

## 1표본 런검정

In [3]:
data = ["a", "a", "b", "b", "a", "a", "a", "a", "b", "b", "b", "b",
        "a", "b", "a", "a", "b", "b", "a", "a", "b", "b", "b", "a",
         "a", "b", "b", "a", "b"]

In [4]:
### 전처리
change_data = [1 if i == "a" else 0 for i in data]
change_data

[1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0]

In [5]:
### 1 표본 런검정 (범주형일 때)
from statsmodels.sandbox.stats.runs import runstest_1samp

# H0 : 데이터가 무작위 배열이다.
# H1 : 데이터가 무작위 배열이 아니다.

runstest_1samp(change_data)

(-0.3721438547031917, 0.7097857460625617)

In [6]:
### 연속형 데이터

data = [50, 60, 70, 40, 30, 20, 10, 70, 80, 100]
data

[50, 60, 70, 40, 30, 20, 10, 70, 80, 100]

In [7]:
from statsmodels.sandbox.stats.runs import runstest_1samp

s, p = runstest_1samp(data,                ## 원본데이터
                      cutoff="median"      #  데이터 중앙값 기준으로 이진화
                      )

print(f"검정통계량 : {s}")
print(f"검정통계량의 p-value : {p}")
print("귀무가설 채택" if p > 0.05 else "귀무가설 기각")

검정통계량 : -1.0062305898749053
검정통계량의 p-value : 0.31430466047385397
귀무가설 채택

## 2표본 런검정

In [8]:
data1 = [23, 42, 36, 27, 48, 52, 35, 31]
data2 = [43, 56, 38, 20, 46, 51, 36]

In [9]:
### 연속형 변수 float 타입으로 변경

data1 = np.array(data1, dtype="float")
data2 = np.array(data2, dtype="float")

data1

array([23., 42., 36., 27., 48., 52., 35., 31.])

In [10]:
## 2표본 런검정
from statsmodels.sandbox.stats.runs import runstest_2samp

# H0 : 두 데이터는 동일한 분포를 가진다. 
# H1 : 두 데이터는 서로 다른 분포를 가진다.

s, p = runstest_2samp(data1, data2)

print(f"검정통계량의 p-value : {p}")
print("귀무가설 채택" if p > 0.05 else "귀무가설 기각")

ties detected
검정통계량의 p-value : 0.9856795756756671
귀무가설 채택

In [11]:
print("""
유의수준 5%하에서 귀무가설을 채택한다. 즉, 두 데이터는 동일한 분포를 가진다.
""")

유의수준 5%하에서 귀무가설을 채택한다. 즉, 두 데이터는 동일한 분포를 가진다.

# <부호 검정>

## 1 표본 부호 검정

## Q. 어떤 공장에서 생산하는 부품의 길이가 200mm가 되도록 설계되었습니다. 품질관리팀에서 최근 생산된 부품 10개를 무작위로 선택하여 길이를 측정한 결과는 다음과 같습니다. 부품의 길이가 설계값 200mm와 차이가 있는지 검정하시오.

In [31]:
### 원본 데이터
data = [203, 204, 197, 195, 201, 205, 198, 199, 194, 207]
data

[203, 204, 197, 195, 201, 205, 198, 199, 194, 207]

In [34]:
### 넘파이 배열로 변환
data = np.array(data)
data

array([203, 204, 197, 195, 201, 205, 198, 199, 194, 207])

In [35]:
### 1 표본 부호검정
from statsmodels.stats.descriptivestats import sign_test

# H0 : 부품 길이의 중앙값이 200mm이다.
# H1 : 부품 길이의 중앙값이 200mm이 아니다.

s, p = sign_test(data-200)

print(f"검정통계량 : {s}")
print(f"검정통계량의 p-value : {p}")
print("귀무가설 채택" if p > 0.05 else "귀무가설 기각")

검정통계량 : 0.0
검정통계량의 p-value : 1.0
귀무가설 채택

## 대응 표본 부호 검정 (쌍체 부호검정??)

## Q. 8명의 학생을 대상으로 새로운 학습법을 적용하기 전과 후의 시험 점수를 측정하였습니다. 새로운 학습법이 학습 효과에 영향을 주는지 검정하시오.

In [72]:
data1 = [79, 96, 85, 69, 88, 75, 83, 88]
data2 = [70, 88, 73, 74, 75, 79, 77, 81]

In [73]:
df = pd.DataFrame({
                   "학생ID" : [1,2,3,4,5,6,7,8],
                   "적용전" : data1,
                   "적용후" : data2       
                  })
df

   학생ID  적용전  적용후
0     1   79   70
1     2   96   88
2     3   85   73
3     4   69   74
4     5   88   75
5     6   75   79
6     7   83   77
7     8   88   81

In [74]:
### 원본 데이터
df

   학생ID  적용전  적용후
0     1   79   70
1     2   96   88
2     3   85   73
3     4   69   74
4     5   88   75
5     6   75   79
6     7   83   77
7     8   88   81

In [75]:
### 그룹 나누기

gBefore = df["적용전"].to_numpy()
gAfter = df["적용후"].to_numpy()

In [76]:
### 대응 표본 부호 검정
from statsmodels.stats.descriptivestats import sign_test

# H0 : (적용 전 - 적용 후)의 중앙값이 0이다. (학습법이 학습효과에 영향을 주지 않는다.)
# H1 : (적용 전 - 적용 후)의 중앙값이 0이 아니다. (학습법이 학습효과에 영향을 준다.)

s, p = sign_test(gBefore - gAfter)              ### 순서 바뀌어도 양측검정일 때는 결과 동일

print(f"검정통계량 : {s}")
print(f"검정통계량의 p-value : {p}")
print("귀무가설 채택" if p > 0.05 else "귀무가설 기각")

검정통계량 : 2.0
검정통계량의 p-value : 0.2890625
귀무가설 채택

In [77]:
print("""
유의수준 5%하에서 귀무가설을 채택한다. 즉, (적용전- 적용후)의 중앙값이 0이다. 학습법이 학습효과에 영향을 주지 않는다.
""")

유의수준 5%하에서 귀무가설을 채택한다. 즉, (적용전- 적용후)의 중앙값이 0이다. 학습법이 학습효과에 영향을 주지 않는다.