# 작업 3유형 (파이썬)

```
나는 광고클릭에 목마르다
```

<a href="https://open.kakao.com/o/gJl1ud2c" style="padding: 10px 20px; font-size: 16px; cursor: pointer; background-color:rgb(135, 6, 116); color: white; border: none; border-radius: 5px; text-decoration: none;">오픈톡방 (pw: dbscan)</a>

### 업데이트 작업중 입니다. 우선 아래 링크에 존재하는 문제들 부터 풀어보셔유
https://www.datamanim.com/dataset/97_scipy/scipy.html  

https://www.datamanim.com/dataset/03_dataq/typethree.html   (adp 통계 기출 파트)

```{attention} 
제공된 데이터(bcc.csv)는 암 환자와 정상인의 리지스틴 수치에 대한 자료이며,     
두 집단의 로그 리지스틴 값에 차이가 있는지를 검정하려고 한다.      
소문항별로 답을 구한 후, 구한 답을 제시된 [제출 형식]에 맞춰 답안 제출 페이지에 입력하시오. (단, 모델은 절편항을 포함한다.)     
````

In [16]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/master/krdatacertificate/s1.csv')
df.head()

   Resistin  Classification
0   7.99585               1
1   4.06405               1
2   9.27715               1
3  12.76600               1
4  10.57635               1

```{admonition} Question 1-1 
두 집단의 로그 리지스틴 값의 분산에 차이가 있는지를 알아보기 위해      
F-검정을 수행할 때 검정통계량의 값을 구하여라.       
(단, 분자의 자유도가 분모의 자유도보다 크도록 하여라. 반올림하여 소수 셋째 자리까지 작성)
```

In [29]:
import numpy as np
cls_1 = df[df['Classification'] ==1]['Resistin']
cls_2 = df[df['Classification'] ==2]['Resistin']

cls_1_log = np.log(cls_1) 
cls_2_log = np.log(cls_2)

cls_1_var = np.var(cls_1_log,ddof=1) # 표본 분산 ddof =1
cls_2_var = np.var(cls_2_log,ddof=1) 

if cls_1_var > cls_2_var:
    f_stat = cls_1_var / cls_2_var
else:
    f_stat = cls_2_var / cls_1_var

round_result = round(f_stat,3)
print(round_result)

1.348

```{admonition} Question 1-2 
두 집단의 로그 리지스틴 값에 대한 합동 분산 추정량을 구하여라.      
반올림하여 소수 셋째 자리까지 작성
```

In [31]:
n1 = len(cls_1)
n2 = len(cls_2)

var_pooled = ((n1 - 1) * cls_1_var + (n2-1) * cls_2_var) / (n1+n2-2)
print(round(var_pooled,3))

0.449

```{admonition} Question 1-3 
2번 문제에서 구한 합동 분산 추정량을 이용하여 두 집단의 로그 리지스틴 값에 
유의미한 차이가 있는지 독립표본 t-검정을 수행하고 p-값을 구하여라. (반올림하여 소수 셋째 자리까지 작성)
```

In [41]:
# method1
from scipy import stats

m1 = cls_1_log.mean()
m2 = cls_2_log.mean()


se     = var_pooled*(1/n1 + 1/n2) # 표준오차
t_stat = (m1-m2) / np.sqrt(se)
p_v    = 2*(1-stats.t.cdf(abs(t_stat),df = n1+n2-2))
print(round(p_v,3))


# method2
t_pv = stats.ttest_ind(cls_1_log,cls_2_log)[1]
print(round(t_pv,3))

0.003
0.003

## 이전 자료

```{admonition} Question 
**정규분포확률 P[Z< 1.23]의 값을 구하여라**
```

```{admonition} Question 
**P[-z <= Z <= z]=0.83을 만족시키는 양의 실수 z를 구하라**
```

```{admonition} Question 
**확률변수 X가 N(74, 16)을 따른다고 하였을 때 P[63<X<81]을 계산하라**
```

```{admonition} Question 
어느 학교의 시험 평균이 72점이고 표준편차가 23인 정규분포를 따른다고 한다. 한 학생의 점수가 다음과 같을 확률을 구하여라    
(1) 83.2점 이상의 점수를 받는다.    
(2) 63점 이하의 점수를 받는다.    
(3) 69.5점에서 87.3점 사이의 점수를 받는다.     
```

```{admonition} Question 
어떤 농가의 있는 사과의 무게는 평균이 453 g이고 표준편차가 31.3 g인 정규분포를 따른다고 한다.     
(1) 하나의 사과를 임의로 선택하여 무게를 재었을 때, 무게가 422.2 g에서 464.25 g 사이일 확률은 얼마인가?    
(2) 9개의 배를 임의로 선택하여 무게의 평균값이 422.2 g에서 464.25 g 사이일 확률은 얼마인가?      
```

```{admonition} Question 
평균이 62이고 분산이 121인 모집단에서 임의추출한 표본에 대하여 생각해 보자.     
(1) 표본의 크기가 64일 때 표본평균이 구간 (61.8, 65.3)에 있을 확률은?     
(2) 표본의 크기가 100일 때 표본평균이 구간 (61.8, 65.3)에 있을 확률은?     
```

```{admonition} Question 
어느 마을의 남자의 키는 평균이 172.3 cm이고 표준편차가 5.1 cm인 정규분포 를 따른다고 한다. 그 마을의 양장점에서 남자들 키의 80% 범위를 목표로 하여 제품을 생산하려고 한다. 원단을 최대한 줄이고자는 방향으로 전략을 짤 때 이들이 목표로 세우려는 키의 범위를 구하라.
```

```{admonition} Question 
어느 회사에서 새로운 제품을 출시했다. 마케팅 팀은 광고 캠페인을 통해 제품에 대한 관심을 증가시키기를 희망하고 있다. 이전의 경험에 따르면, 광고를 본 사람들 중 30%만이 제품을 구매할 의사가 있었다. 만약 무작위로 선정된 한 사람이 광고를 보았다면, 이 사람이 제품을 구매할 확률을 계산하라.
```

```{admonition} Question 
정팔면체 주사위에 1~8까지 숫자가 적혀있다. 8번 주사위를 던졌을 때 다음의 확률을 구하여라     
(1) 숫자 1이 한 번만 나오는 경우    
(2) 숫자 2 또는 4가 5회 이상 나오는 경우    
(3) 숫자 3이 적어도 3회 나오는 경우    
(3) 숫자 5가 많아야 3회 나오는 경우    
```

```{admonition} Question 
한 스타트업 회사가 새로운 제품을 출시하였고, 각 고객 방문 시 제품 구매 확률이 0.1이라고 한다.    
(1) 최소 한 명의 고객이 제품을 구매하기 까지 방문하는 고객 수가 4명일 확률은?    
(2) 회사는 최소 한 명의 고객이 제품을 구매하기까지 방문하는 고객 수가 5명 이하일 확률은?     
```

```{admonition} Question 
특정지역의 성별에 따른 감기 검사결과이다.    
(1) 다섯명의 사람을 임의로 선택하였을 때, 감기에 양성 반응인 사람이 1명일 확률은?    
(2) 열두명의 사람을 임의로 선택하였을 때, 감기에 양성 반응인 사람이 6명 이상일 확률은?         
(3) 4명의 남자, 2명의 여자가 임의로 선택되었을 때, 감기에 양성 반응인 사람이 없을 확률은?        
```
<table>
<tr>
    <th>감기</th>
    <th>양성</th>
    <th>음성</th> 
</tr>

<tr>
    <td>남자</td> 
    <td>16</td> 
    <td>54</td>
</tr>

<tr>
    <td>여자</td> 
    <td>12</td> 
    <td>23</td>   
</tr>

</table>

```{admonition} Question 
나사 생산 공장에서 52개를 생산 했는데, 이중 7개의 불량품이 섞여 있었다.
어느 고객이 15개를 구매 했는데 이 중에서 불량인 나사가 많아야 3개일 확률을 구하여라.
```

```{admonition} Question 
어느 회사에서 사원을 8명 모집하기 위해 신문에 광고를 내었더니 15명의 남자와 8명의 여자가 지원하였다.
임의로 8명을 선택한다고 한다면 8명 중 여자가 3명 이상일 확률을 구하라. 예상되는 여자 신입사원은 몇 명이 되겠는가?
```

```{admonition} Question 
마케팅 팀이 새로운 광고 캠페인을 시작했다. 광고를 본 후 제품을 구매하는 고객의 비율이 12%로 알려져 있다.    
(1) 적어도 한 명의 고객이 제품을 구매하기까지 광고를 본 평균 고객 수는 몇 명인가?     
(2) 적어도 3명의 고객이 제품을 구매하기까지 광고를 본 고객 수가 10명을 초과할 확률은 얼마인가?    
(3) 5명의 고객이 제품을 구매하기 까지 필요한 광고를 본 고객수의 기대값과 분산은 얼마인가?     
```

```{admonition} Question 
어떤 골목 특정 지점에서 하루 평균 3회의 사고가 발생한다고 한다. 특정하루 동안    
(1) 0회의 사고가 발생할 확률은?      
(2) 4회 이상의 사고가 발생할 확률은?    
포아송분포를 이용하여 풀어라
```

```{admonition} Question 
어느 중학교는 지난 5년간 매년 300명(10개반, 각 반 30명)의 신입생을 받았다. 각 반에서 평균적으로 2명의 학생이 왼손잡이인 것으로 나타났다. 올해에도 왼손잡이 학생의 비율이 예년과 같다고 가정할 때, 임의로 한 개의 반 학생들 중 왼손잡이 학생이 4명 이하일 확률은 얼마인가?     
포아송 분포를 이용하여 풀어라
```

```{admonition} Question 
지수분포를 이용하여 풀어라     
(1) 평균 사건 발생률이 분당 2회인 시스템에서, 다음 사건이 발생하기까지 1분 이내일 확률은 얼마인가?    
(2) 같은 시스템에서, 다음 사건이 발생하기까지 3분 이상 걸릴 확률은 얼마인가?     
(3) 해당 시스템에서 다음 사건이 발생하기까지의 시간의 기대값과 표준편차는 얼마인가?     
```

```{admonition} Question 
어느 나사 공장에서 나사의 길이에 대한 조사를 한다. 50개 샘플 나사들에 대해 다음과 같은 통계량을 얻었다.
Σ𝑋𝑖2 =162, Σ𝑋𝑖 =77 일 때, 평균 길이를 추정하고 그 추정량의 표준 오차를 구하여라
```

```{admonition} Question 
한 카페에서 판매하는 음료의 종류(커피, 차, 주스)에 대한 고객 선호도 조사 결과가 40, 30, 30이고, 우리는 각 음료가 동등하게 선호된다고 가정합니다. 고객의 선호도가 균일한지 검정하려한다. 카이제곱 통계량을 구하여라
```

```{admonition} Question 
두 지역의 3가지 과일에 대한 수확량을 나타냈다. 두지역의 과일 수확량 분포의 차이가 존재하는지 확인하라
```
<table>
<tr>
    <th></th>
    <th>사과</th>
    <th>포도</th> 
    <th>오렌지</th> 
</tr>

<tr>
    <td>지역A</td> 
    <td>124</td> 
    <td>44</td>
    <td>215</td>
</tr>

<tr>
    <td>지역B</td> 
    <td>295</td> 
    <td>145</td>   
    <td>442</td>   
</tr>

</table>

```{admonition} Question 
130명 유저들에게 물건 구매에 대한 의사를 광고 전후로 비교하여 설문 조사하였다.
광고 시정 전과 후의 구매의사를 차이가 있는지 검정하라
```

In [6]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/mac1.csv').head()
df

  광고 시청 전 구매 의사 광고 시청 후 구매 의사
0            no           yes
1            no            no
2            no           yes
3           yes            no
4            no           yes

```{admonition} Question 
두 학생의 다 회차의 수행평가 성적은 다음과 같다
a = [40,50,55,42,60,80]
b = [30,55,60,76]
두학생 성적간의 차이가 존재한다고 볼 수 있는지 검정하라
```

## t- 검정

### 일표본 t-검정

### 대응표본 t-검정

### 독립표본 t-검정

## 정규성 검정

## 등분산 검정

## 분산분석

### One-way ANOVA

### Two-way ANOVA

## 카이제곱 검정

### 독립성 검정

### 동질성 검정

### 적합성 검정

## 순위검정

### 윌콕슨 순위합 검정

### 크루스칼 - 왈리스 검정

## 부호검정

### 부호검정

### 맥네마 검정

## 다변량 추론

### 다중 회귀 분석